In [98]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
%matplotlib inline
import warnings 
warnings.filterwarnings('ignore')
from datetime import datetime
import seaborn as sns
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [2]:
train=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")

In [3]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [5]:
train.columns.difference(test.columns)

Index(['SalePrice'], dtype='object')

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [7]:
train.isna().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [8]:
train['Source']='train'
test['Source']='test'

In [9]:
test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,Source
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,test
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,test
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,test
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,test
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,0,NaN,NaN,NaN,0,1,2010,WD,Normal,test

In [10]:
df=pd.concat([train,test])
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 82 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             2919 non-null   int64
 1   MSSubClass     2919 non-null   int64
 2   MSZoning       2915 non-null   object
 3   LotFrontage    2433 non-null   float64
 4   LotArea        2919 non-null   int64
 5   Street         2919 non-null   object
 6   Alley          198 non-null    object
 7   LotShape       2919 non-null   object
 8   LandContour    2919 non-null   object
 9   Utilities      2917 non-null   object
 10  LotConfig      2919 non-null   object
 11  LandSlope      2919 non-null   object
 12  Neighborhood   2919 non-null   object
 13  Condition1     2919 non-null   object
 14  Condition2     2919 non-null   object
 15  BldgType       2919 non-null   object
 16  HouseStyle     2919 non-null   object
 17  OverallQual    2919 non-null   int64
 18  OverallCond    2919 non-null   int64
 19  YearBuilt      2919 non-null   int64
 20  YearRemodAdd   2919 non-null   int64
 21  RoofStyle      2919 non-null   object
 22  RoofMatl       2919 non-null   object
 23  Exterior1st    2918 non-null   object
 24  Exterior2nd    2918 non-null   object
 25  MasVnrType     2895 non-null   object
 26  MasVnrArea     2896 non-null   float64
 27  ExterQual      2919 non-null   object
 28  ExterCond      2919 non-null   object
 29  Foundation     2919 non-null   object
 30  BsmtQual       2838 non-null   object
 31  BsmtCond       2837 non-null   object
 32  BsmtExposure   2837 non-null   object
 33  BsmtFinType1   2840 non-null   object
 34  BsmtFinSF1     2918 non-null   float64
 35  BsmtFinType2   2839 non-null   object
 36  BsmtFinSF2     2918 non-null   float64
 37  BsmtUnfSF      2918 non-null   float64
 38  TotalBsmtSF    2918 non-null   float64
 39  Heating        2919 non-null   object
 40  HeatingQC      2919 non-null   object
 41  CentralAir     2919 non-null   object
 42  Electrical     2918 non-null   object
 43  1stFlrSF       2919 non-null   int64
 44  2ndFlrSF       2919 non-null   int64
 45  LowQualFinSF   2919 non-null   int64
 46  GrLivArea      2919 non-null   int64
 47  BsmtFullBath   2917 non-null   float64
 48  BsmtHalfBath   2917 non-null   float64
 49  FullBath       2919 non-null   int64
 50  HalfBath       2919 non-null   int64
 51  BedroomAbvGr   2919 non-null   int64
 52  KitchenAbvGr   2919 non-null   int64
 53  KitchenQual    2918 non-null   object
 54  TotRmsAbvGrd   2919 non-null   int64
 55  Functional     2917 non-null   object
 56  Fireplaces     2919 non-null   int64
 57  FireplaceQu    1499 non-null   object
 58  GarageType     2762 non-null   object
 59  GarageYrBlt    2760 non-null   float64
 60  GarageFinish   2760 non-null   object
 61  GarageCars     2918 non-null   float64
 62  GarageArea     2918 non-null   float64
 63  GarageQual     2760 non-null   object
 64  GarageCond     2760 non-null   object
 65  PavedDrive     2919 non-null   object
 66  WoodDeckSF     2919 non-null   int64
 67  OpenPorchSF    2919 non-null   int64
 68  EnclosedPorch  2919 non-null   int64
 69  3SsnPorch      2919 non-null   int64
 70  ScreenPorch    2919 non-null   int64
 71  PoolArea       2919 non-null   int64
 72  PoolQC         10 non-null     object
 73  Fence          571 non-null    object
 74  MiscFeature    105 non-null    object
 75  MiscVal        2919 non-null   int64
 76  MoSold         2919 non-null   int64
 77  YrSold         2919 non-null   int64
 78  SaleType       2918 non-null   object
 79  SaleCondition  2919 non-null   object
 80  SalePrice      1460 non-null   float64
 81  Source         2919 non-null   object
dtypes: float64(12), int64(26), object(44)
memory usage: 1.8+ MB

In [11]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,2919.000000,2919.000000,2433.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2896.000000,2918.000000,...,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,1460.000000
mean,1460.000000,57.137718,69.305795,10168.114080,6.089072,5.564577,1971.312778,1984.264474,102.201312,441.423235,...,93.709832,47.486811,23.098321,2.602261,16.062350,2.251799,50.825968,6.213087,2007.792737,180921.195890
std,842.787043,42.517628,23.344905,7886.996359,1.409947,1.113131,30.291442,20.894344,179.334253,455.610826,...,126.526589,67.575493,64.244246,25.188169,56.184365,35.663946,567.402211,2.714762,1.314964,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,730.500000,20.000000,59.000000,7478.000000,5.000000,5.000000,1953.500000,1965.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129975.000000
50%,1460.000000,50.000000,68.000000,9453.000000,6.000000,5.000000,1973.000000,1993.000000,0.000000,368.500000,...,0.000000,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,2189.500000,70.000000,80.000000,11570.000000,7.000000,6.000000,2001.000000,2004.000000,164.000000,733.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,2919.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 82 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             2919 non-null   int64
 1   MSSubClass     2919 non-null   int64
 2   MSZoning       2915 non-null   object
 3   LotFrontage    2433 non-null   float64
 4   LotArea        2919 non-null   int64
 5   Street         2919 non-null   object
 6   Alley          198 non-null    object
 7   LotShape       2919 non-null   object
 8   LandContour    2919 non-null   object
 9   Utilities      2917 non-null   object
 10  LotConfig      2919 non-null   object
 11  LandSlope      2919 non-null   object
 12  Neighborhood   2919 non-null   object
 13  Condition1     2919 non-null   object
 14  Condition2     2919 non-null   object
 15  BldgType       2919 non-null   object
 16  HouseStyle     2919 non-null   object
 17  OverallQual    2919 non-null   int64
 18  OverallCond    2919 non-null   int64
 19  YearBuilt      2919 non-null   int64
 20  YearRemodAdd   2919 non-null   int64
 21  RoofStyle      2919 non-null   object
 22  RoofMatl       2919 non-null   object
 23  Exterior1st    2918 non-null   object
 24  Exterior2nd    2918 non-null   object
 25  MasVnrType     2895 non-null   object
 26  MasVnrArea     2896 non-null   float64
 27  ExterQual      2919 non-null   object
 28  ExterCond      2919 non-null   object
 29  Foundation     2919 non-null   object
 30  BsmtQual       2838 non-null   object
 31  BsmtCond       2837 non-null   object
 32  BsmtExposure   2837 non-null   object
 33  BsmtFinType1   2840 non-null   object
 34  BsmtFinSF1     2918 non-null   float64
 35  BsmtFinType2   2839 non-null   object
 36  BsmtFinSF2     2918 non-null   float64
 37  BsmtUnfSF      2918 non-null   float64
 38  TotalBsmtSF    2918 non-null   float64
 39  Heating        2919 non-null   object
 40  HeatingQC      2919 non-null   object
 41  CentralAir     2919 non-null   object
 42  Electrical     2918 non-null   object
 43  1stFlrSF       2919 non-null   int64
 44  2ndFlrSF       2919 non-null   int64
 45  LowQualFinSF   2919 non-null   int64
 46  GrLivArea      2919 non-null   int64
 47  BsmtFullBath   2917 non-null   float64
 48  BsmtHalfBath   2917 non-null   float64
 49  FullBath       2919 non-null   int64
 50  HalfBath       2919 non-null   int64
 51  BedroomAbvGr   2919 non-null   int64
 52  KitchenAbvGr   2919 non-null   int64
 53  KitchenQual    2918 non-null   object
 54  TotRmsAbvGrd   2919 non-null   int64
 55  Functional     2917 non-null   object
 56  Fireplaces     2919 non-null   int64
 57  FireplaceQu    1499 non-null   object
 58  GarageType     2762 non-null   object
 59  GarageYrBlt    2760 non-null   float64
 60  GarageFinish   2760 non-null   object
 61  GarageCars     2918 non-null   float64
 62  GarageArea     2918 non-null   float64
 63  GarageQual     2760 non-null   object
 64  GarageCond     2760 non-null   object
 65  PavedDrive     2919 non-null   object
 66  WoodDeckSF     2919 non-null   int64
 67  OpenPorchSF    2919 non-null   int64
 68  EnclosedPorch  2919 non-null   int64
 69  3SsnPorch      2919 non-null   int64
 70  ScreenPorch    2919 non-null   int64
 71  PoolArea       2919 non-null   int64
 72  PoolQC         10 non-null     object
 73  Fence          571 non-null    object
 74  MiscFeature    105 non-null    object
 75  MiscVal        2919 non-null   int64
 76  MoSold         2919 non-null   int64
 77  YrSold         2919 non-null   int64
 78  SaleType       2918 non-null   object
 79  SaleCondition  2919 non-null   object
 80  SalePrice      1460 non-null   float64
 81  Source         2919 non-null   object
dtypes: float64(12), int64(26), object(44)
memory usage: 1.8+ MB

In [13]:
total=df.isna().sum().sort_values(ascending=False)
percent=(((df.isna().sum())/(df.isna().count()))*100).sort_values(ascending=False)
x=pd.concat([total,percent],axis=1,keys=('Total','Percent'))
x

              Total    Percent
PoolQC         2909  99.657417
MiscFeature    2814  96.402878
Alley          2721  93.216855
Fence          2348  80.438506
SalePrice      1459  49.982871
...             ...        ...
1stFlrSF          0   0.000000
2ndFlrSF          0   0.000000
LowQualFinSF      0   0.000000
GrLivArea         0   0.000000
Source            0   0.000000

[82 rows x 2 columns]

In [14]:
df.columns[df.isna().mean()>0.7]

Index(['Alley', 'PoolQC', 'Fence', 'MiscFeature'], dtype='object')

In [15]:
df=df.drop(['Alley', 'PoolQC', 'Fence', 'MiscFeature'],axis=1)

In [16]:
df=df.dropna(how='all').reset_index(drop=True)
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Source
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,2,2008,WD,Normal,208500.0,train
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,5,2007,WD,Normal,181500.0,train
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,9,2008,WD,Normal,223500.0,train
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,0,2,2006,WD,Abnorml,140000.0,train
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,12,2008,WD,Normal,250000.0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,RM,21.0,1936,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,6,2006,WD,Normal,NaN,test
2915,2916,160,RM,21.0,1894,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,4,2006,WD,Abnorml,NaN,test
2916,2917,20,RL,160.0,20000,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,9,2006,WD,Abnorml,NaN,test
2917,2918,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,700,7,2006,WD,Normal,NaN,test
2918,2919,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,11,2006,WD,Normal,NaN,test

In [17]:
df.loc[df.isnull().mean(axis=1)>0.7]

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, MiscVal, MoSold, YrSold, SaleType, SaleCondition, SalePrice, Source]
Index: []

[0 rows x 78 columns]

In [18]:
df.isnull().sum().sort_values(ascending=False)

SalePrice       1459
FireplaceQu     1420
LotFrontage      486
GarageQual       159
GarageFinish     159
                ...
CentralAir         0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
Source             0
Length: 78, dtype: int64

In [19]:
df.isnull().sum().sort_values(ascending=False)

SalePrice       1459
FireplaceQu     1420
LotFrontage      486
GarageQual       159
GarageFinish     159
                ...
CentralAir         0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
Source             0
Length: 78, dtype: int64

In [20]:
df[df.duplicated()]

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, MiscVal, MoSold, YrSold, SaleType, SaleCondition, SalePrice, Source]
Index: []

[0 rows x 78 columns]

In [21]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Id,2919.0,NaN,NaN,NaN,1460.0,842.787043,1.0,730.5,1460.0,2189.5,2919.0
MSSubClass,2919.0,NaN,NaN,NaN,57.137718,42.517628,20.0,20.0,50.0,70.0,190.0
MSZoning,2915,5,RL,2265,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LotFrontage,2433.0,NaN,NaN,NaN,69.305795,23.344905,21.0,59.0,68.0,80.0,313.0
LotArea,2919.0,NaN,NaN,NaN,10168.11408,7886.996359,1300.0,7478.0,9453.0,11570.0,215245.0
...,...,...,...,...,...,...,...,...,...,...,...
YrSold,2919.0,NaN,NaN,NaN,2007.792737,1.314964,2006.0,2007.0,2008.0,2009.0,2010.0
SaleType,2918,9,WD,2525,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SaleCondition,2919,6,Normal,2402,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SalePrice,1460.0,NaN,NaN,NaN,180921.19589,79442.502883,34900.0,129975.0,163000.0,214000.0,755000.0
Source,2919,2,train,1460,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df.columns[df.isna().sum()>=1]

Index(['MSZoning', 'LotFrontage', 'Utilities', 'Exterior1st', 'Exterior2nd',
       'MasVnrType', 'MasVnrArea', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF',
       'TotalBsmtSF', 'Electrical', 'BsmtFullBath', 'BsmtHalfBath',
       'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'SaleType', 'SalePrice'],
      dtype='object')

In [23]:
numeric_col=df.select_dtypes(include=np.number).drop(columns=['SalePrice','Id'])
#numeric_col.drop(columns=['SalePrice','Id'])
numeric_col=numeric_col.columns
numeric_col

Index(['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces',
       'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold'],
      dtype='object')

In [24]:
num_na_col=numeric_col[df[numeric_col].isna().sum()>=1]
num_na_col

Index(['LotFrontage', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF',
       'TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath', 'GarageYrBlt',
       'GarageCars', 'GarageArea'],
      dtype='object')

In [25]:
# col=['LotFrontage', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF',
#        'TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath', 'GarageYrBlt',
#        'GarageCars', 'GarageArea']

# numeric_col[col]

In [26]:
# df[col].nunique()

In [27]:
#df.drop(columns=['Id','SalePrice'],axis=1,inplace=True)
df[num_na_col]=df[num_na_col].fillna(df[num_na_col].median())
df[num_na_col].isna().sum()

LotFrontage     0
MasVnrArea      0
BsmtFinSF1      0
BsmtFinSF2      0
BsmtUnfSF       0
TotalBsmtSF     0
BsmtFullBath    0
BsmtHalfBath    0
GarageYrBlt     0
GarageCars      0
GarageArea      0
dtype: int64

In [28]:
for col in numeric_col:
    low=df[col].quantile(0.25)
    up=df[col].quantile(0.75)
    iqr=up-low
    

    low_outlier = low-1.5*iqr
    up_outlier=up+1.5*iqr
    

    df.loc[(df[col]<low_outlier) | (df[col]>up_outlier),col]=df[col].median()

In [29]:
df[numeric_col].describe().T

,count,mean,std,min,25%,50%,75%,max
MSSubClass,2919.0,48.597122,28.536860,20.0,20.0,50.0,60.0,120.0
LotFrontage,2919.0,68.267900,13.190263,33.0,60.0,68.0,75.0,105.0
LotArea,2919.0,9220.133265,3165.292613,1470.0,7484.0,9453.0,11059.0,17671.0
OverallQual,2919.0,6.095923,1.397288,2.0,5.0,6.0,7.0,10.0
OverallCond,2919.0,5.414526,0.761124,4.0,5.0,5.0,6.0,7.0
YearBuilt,2919.0,1971.603631,29.849545,1885.0,1954.0,1973.0,2001.0,2010.0
YearRemodAdd,2919.0,1984.264474,20.894344,1950.0,1965.0,1993.0,2004.0,2010.0
MasVnrArea,2919.0,59.540596,101.842816,0.0,0.0,0.0,100.5,408.0
BsmtFinSF1,2919.0,430.722850,426.299255,0.0,0.0,368.5,726.5,1812.0
BsmtFinSF2,2919.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
BsmtUnfSF,2919.0,535.841384,403.295949,0.0,220.0,467.0,780.0,1680.0
TotalBsmtSF,2919.0,1054.844639,350.915323,105.0,816.0,989.5,1270.5,2062.0
1stFlrSF,2919.0,1137.806098,344.464790,334.0,876.0,1082.0,1364.0,2151.0
2ndFlrSF,2919.0,331.408359,421.607840,0.0,0.0,0.0,702.0,1721.0
LowQualFinSF,2919.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
GrLivArea,2919.0,1459.453237,428.593394,334.0,1126.0,1444.0,1714.0,2668.0
BsmtFullBath,2919.0,0.427544,0.520461,0.0,0.0,0.0,1.0,2.0
BsmtHalfBath,2919.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
FullBath,2919.0,1.565262,0.545816,0.0,1.0,2.0,2.0,3.0
HalfBath,2919.0,0.380267,0.502872,0.0,0.0,0.0,1.0,2.0
BedroomAbvGr,2919.0,2.812264,0.705195,1.0,2.0,3.0,3.0,4.0
KitchenAbvGr,2919.0,1.000000,0.000000,1.0,1.0,1.0,1.0,1.0
TotRmsAbvGrd,2919.0,6.355601,1.415048,2.0,5.0,6.0,7.0,10.0
Fireplaces,2919.0,0.588558,0.626373,0.0,0.0,1.0,1.0,2.0
GarageYrBlt,2919.0,1978.303186,24.150294,1906.0,1962.0,1979.0,2001.0,2010.0
GarageCars,2919.0,1.754711,0.741036,0.0,1.0,2.0,2.0,3.0
GarageArea,2919.0,463.703666,200.121090,0.0,320.0,480.0,576.0,959.0
WoodDeckSF,2919.0,81.394313,105.110877,0.0,0.0,0.0,160.0,418.0
OpenPorchSF,2919.0,35.366221,43.247235,0.0,0.0,26.0,56.0,175.0
EnclosedPorch,2919.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
3SsnPorch,2919.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
ScreenPorch,2919.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
PoolArea,2919.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
MiscVal,2919.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
MoSold,2919.0,6.213087,2.714762,1.0,4.0,6.0,8.0,12.0
YrSold,2919.0,2007.792737,1.314964,2006.0,2007.0,2008.0,2009.0,2010.0

In [31]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Source
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,2,2008,WD,Normal,208500.0,train
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,5,2007,WD,Normal,181500.0,train
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,9,2008,WD,Normal,223500.0,train
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,0,2,2006,WD,Abnorml,140000.0,train
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,12,2008,WD,Normal,250000.0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,50,RM,68.0,1936,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,6,2006,WD,Normal,NaN,test
2915,2916,50,RM,68.0,1894,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,4,2006,WD,Abnorml,NaN,test
2916,2917,20,RL,68.0,9453,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,9,2006,WD,Abnorml,NaN,test
2917,2918,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,7,2006,WD,Normal,NaN,test
2918,2919,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,11,2006,WD,Normal,NaN,test

In [34]:
df.drop(columns=['PoolArea','ScreenPorch','3SsnPorch','EnclosedPorch','KitchenAbvGr','BsmtHalfBath','LowQualFinSF','BsmtFinSF2'],axis=1,inplace=True)

In [35]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,PavedDrive,WoodDeckSF,OpenPorchSF,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Source
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,Y,0,61,0,2,2008,WD,Normal,208500.0,train
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,Y,298,0,0,5,2007,WD,Normal,181500.0,train
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,Y,0,42,0,9,2008,WD,Normal,223500.0,train
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,Y,0,35,0,2,2006,WD,Abnorml,140000.0,train
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,Y,192,84,0,12,2008,WD,Normal,250000.0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,50,RM,68.0,1936,Pave,Reg,Lvl,AllPub,Inside,...,Y,0,0,0,6,2006,WD,Normal,NaN,test
2915,2916,50,RM,68.0,1894,Pave,Reg,Lvl,AllPub,Inside,...,Y,0,24,0,4,2006,WD,Abnorml,NaN,test
2916,2917,20,RL,68.0,9453,Pave,Reg,Lvl,AllPub,Inside,...,Y,0,0,0,9,2006,WD,Abnorml,NaN,test
2917,2918,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,Inside,...,Y,80,32,0,7,2006,WD,Normal,NaN,test
2918,2919,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,Inside,...,Y,190,48,0,11,2006,WD,Normal,NaN,test

In [54]:
category_col=df.select_dtypes(exclude=np.number).columns
df[category_col]

,MSZoning,Street,LotShape,LandContour,LotConfig,LandSlope,Condition1,Condition2,BldgType,HouseStyle,...,Functional,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition,Source
0,RL,Pave,Reg,Lvl,Inside,Gtl,Norm,Norm,1Fam,2Story,...,Typ,NaN,Attchd,RFn,TA,TA,Y,WD,Normal,train
1,RL,Pave,Reg,Lvl,FR2,Gtl,Feedr,Norm,1Fam,1Story,...,Typ,TA,Attchd,RFn,TA,TA,Y,WD,Normal,train
2,RL,Pave,IR1,Lvl,Inside,Gtl,Norm,Norm,1Fam,2Story,...,Typ,TA,Attchd,RFn,TA,TA,Y,WD,Normal,train
3,RL,Pave,IR1,Lvl,Corner,Gtl,Norm,Norm,1Fam,2Story,...,Typ,Gd,Detchd,Unf,TA,TA,Y,WD,Abnorml,train
4,RL,Pave,IR1,Lvl,FR2,Gtl,Norm,Norm,1Fam,2Story,...,Typ,TA,Attchd,RFn,TA,TA,Y,WD,Normal,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,RM,Pave,Reg,Lvl,Inside,Gtl,Norm,Norm,Twnhs,2Story,...,Typ,NaN,NaN,NaN,NaN,NaN,Y,WD,Normal,test
2915,RM,Pave,Reg,Lvl,Inside,Gtl,Norm,Norm,TwnhsE,2Story,...,Typ,NaN,CarPort,Unf,TA,TA,Y,WD,Abnorml,test
2916,RL,Pave,Reg,Lvl,Inside,Gtl,Norm,Norm,1Fam,1Story,...,Typ,TA,Detchd,Unf,TA,TA,Y,WD,Abnorml,test
2917,RL,Pave,Reg,Lvl,Inside,Gtl,Norm,Norm,1Fam,SFoyer,...,Typ,NaN,NaN,NaN,NaN,NaN,Y,WD,Normal,test
2918,RL,Pave,Reg,Lvl,Inside,Mod,Norm,Norm,1Fam,2Story,...,Typ,TA,Attchd,Fin,TA,TA,Y,WD,Normal,test

In [47]:
df[category_col].apply(lambda x:print(x.value_counts()))

RL         2265
RM          460
FV          139
RH           26
C (all)      25
Name: MSZoning, dtype: int64
Pave    2907
Grvl      12
Name: Street, dtype: int64
Reg    1859
IR1     968
IR2      76
IR3      16
Name: LotShape, dtype: int64
Lvl    2622
HLS     120
Bnk     117
Low      60
Name: LandContour, dtype: int64
AllPub    2916
NoSeWa       1
Name: Utilities, dtype: int64
Inside     2133
Corner      511
CulDSac     176
FR2          85
FR3          14
Name: LotConfig, dtype: int64
Gtl    2778
Mod     125
Sev      16
Name: LandSlope, dtype: int64
NAmes      443
CollgCr    267
OldTown    239
Edwards    194
Somerst    182
NridgHt    166
Gilbert    165
Sawyer     151
NWAmes     131
SawyerW    125
Mitchel    114
BrkSide    108
Crawfor    103
IDOTRR      93
Timber      72
NoRidge     71
StoneBr     51
SWISU       48
ClearCr     44
MeadowV     37
BrDale      30
Blmngtn     28
Veenker     24
NPkVill     23
Blueste     10
Name: Neighborhood, dtype: int64
Norm      2511
Feedr      164
Artery      92
RRAn        50
PosN        39
RRAe        28
PosA        20
RRNn         9
RRNe         6
Name: Condition1, dtype: int64
Norm      2889
Feedr       13
Artery       5
PosN         4
PosA         4
RRNn         2
RRAn         1
RRAe         1
Name: Condition2, dtype: int64
1Fam      2425
TwnhsE     227
Duplex     109
Twnhs       96
2fmCon      62
Name: BldgType, dtype: int64
1Story    1471
2Story     872
1.5Fin     314
SLvl       128
SFoyer      83
2.5Unf      24
1.5Unf      19
2.5Fin       8
Name: HouseStyle, dtype: int64
Gable      2310
Hip         551
Gambrel      22
Flat         20
Mansard      11
Shed          5
Name: RoofStyle, dtype: int64
CompShg    2876
Tar&Grv      23
WdShake       9
WdShngl       7
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: RoofMatl, dtype: int64
VinylSd    1025
MetalSd     450
HdBoard     442
Wd Sdng     411
Plywood     221
CemntBd     126
BrkFace      87
WdShing      56
AsbShng      44
Stucco       43
BrkComm       6
AsphShn       2
Stone         2
CBlock        2
ImStucc       1
Name: Exterior1st, dtype: int64
VinylSd    1014
MetalSd     447
HdBoard     406
Wd Sdng     391
Plywood     270
CmentBd     126
Wd Shng      81
BrkFace      47
Stucco       47
AsbShng      38
Brk Cmn      22
ImStucc      15
Stone         6
AsphShn       4
CBlock        3
Other         1
Name: Exterior2nd, dtype: int64
None       1742
BrkFace     879
Stone       249
BrkCmn       25
Name: MasVnrType, dtype: int64
TA    1798
Gd     979
Ex     107
Fa      35
Name: ExterQual, dtype: int64
TA    2538
Gd     299
Fa      67
Ex      12
Po       3
Name: ExterCond, dtype: int64
PConc     1308
CBlock    1235
BrkTil     311
Slab        49
Stone       11
Wood         5
Name: Foundation, dtype: int64
TA    1283
Gd    1209
Ex     258
Fa      88
Name: BsmtQual, dtype: int64
TA    2606
Gd     122
Fa     104
Po       5
Name: BsmtCond, dtype: int64
No    1904
Av     418
Gd     276
Mn     239
Name: BsmtExposure, dtype: int64
Unf    851
GLQ    849
ALQ    429
Rec    288
BLQ    269
LwQ    154
Name: BsmtFinType1, dtype: int64
Unf    2493
Rec     105
LwQ      87
BLQ      68
ALQ      52
GLQ      34
Name: BsmtFinType2, dtype: int64
GasA     2874
GasW       27
Grav        9
Wall        6
OthW        2
Floor       1
Name: Heating, dtype: int64
Ex    1493
TA     857
Gd     474
Fa      92
Po       3
Name: HeatingQC, dtype: int64
Y    2723
N     196
Name: CentralAir, dtype: int64
SBrkr    2671
FuseA     188
FuseF      50
FuseP       8
Mix         1
Name: Electrical, dtype: int64
TA    1492
Gd    1151
Ex     205
Fa      70
Name: KitchenQual, dtype: int64
Typ     2717
Min2      70
Min1      65
Mod       35
Maj1      19
Maj2       9
Sev        2
Name: Functional, dtype: int64
Gd    744
TA    592
Fa     74
Po     46
Ex     43
Name: FireplaceQu, dtype: int64
Attchd     1723
Detchd      779
BuiltIn     186
Basment      36
2Types       23
CarPort      15
Name: GarageType, dtype: int64
Unf    1230
RFn     811
Fin     719
Name: GarageFinish, dtype: int64
TA    2604
Fa     124
Gd      24
Po       5
Ex       3
Name: GarageQual, dtype: int64
TA    2654
Fa      74
Gd      15
Po      14
Ex       3
Name: GarageCond, dtype: int64
Y    2641
N     216
P      62
Name: PavedDrive, dtype: int64
WD       2525
New       239
COD        87
ConLD      26
CWD        12
ConLI       9
ConLw       8
Oth         7
Con         5
Name: SaleType, dtype: int64
Normal     2402
Partial     245
Abnorml     190
Family       46
Alloca       24
AdjLand      12
Name: SaleCondition, dtype: int64
train    1460
test     1459
Name: Source, dtype: int64

MSZoning         None
Street           None
LotShape         None
LandContour      None
Utilities        None
LotConfig        None
LandSlope        None
Neighborhood     None
Condition1       None
Condition2       None
BldgType         None
HouseStyle       None
RoofStyle        None
RoofMatl         None
Exterior1st      None
Exterior2nd      None
MasVnrType       None
ExterQual        None
ExterCond        None
Foundation       None
BsmtQual         None
BsmtCond         None
BsmtExposure     None
BsmtFinType1     None
BsmtFinType2     None
Heating          None
HeatingQC        None
CentralAir       None
Electrical       None
KitchenQual      None
Functional       None
FireplaceQu      None
GarageType       None
GarageFinish     None
GarageQual       None
GarageCond       None
PavedDrive       None
SaleType         None
SaleCondition    None
Source           None
dtype: object

In [74]:
#df.drop(columns=['Neighborhood','Exterior1st','Exterior2nd','Utilities'],axis=1,inplace=True)
df[category_col]

,MSZoning,Street,LotShape,LandContour,LotConfig,LandSlope,Condition1,Condition2,BldgType,HouseStyle,...,Functional,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition,Source
0,RL,Pave,Reg,Lvl,Inside,Gtl,Norm,Norm,1Fam,2Story,...,Typ,Gd,Attchd,RFn,TA,TA,Y,WD,Normal,train
1,RL,Pave,Reg,Lvl,FR2,Gtl,Feedr,Norm,1Fam,1Story,...,Typ,TA,Attchd,RFn,TA,TA,Y,WD,Normal,train
2,RL,Pave,IR1,Lvl,Inside,Gtl,Norm,Norm,1Fam,2Story,...,Typ,TA,Attchd,RFn,TA,TA,Y,WD,Normal,train
3,RL,Pave,IR1,Lvl,Corner,Gtl,Norm,Norm,1Fam,2Story,...,Typ,Gd,Detchd,Unf,TA,TA,Y,WD,Abnorml,train
4,RL,Pave,IR1,Lvl,FR2,Gtl,Norm,Norm,1Fam,2Story,...,Typ,TA,Attchd,RFn,TA,TA,Y,WD,Normal,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,RM,Pave,Reg,Lvl,Inside,Gtl,Norm,Norm,Twnhs,2Story,...,Typ,Gd,NaN,NaN,NaN,NaN,Y,WD,Normal,test
2915,RM,Pave,Reg,Lvl,Inside,Gtl,Norm,Norm,TwnhsE,2Story,...,Typ,Gd,CarPort,Unf,TA,TA,Y,WD,Abnorml,test
2916,RL,Pave,Reg,Lvl,Inside,Gtl,Norm,Norm,1Fam,1Story,...,Typ,TA,Detchd,Unf,TA,TA,Y,WD,Abnorml,test
2917,RL,Pave,Reg,Lvl,Inside,Gtl,Norm,Norm,1Fam,SFoyer,...,Typ,Gd,NaN,NaN,NaN,NaN,Y,WD,Normal,test
2918,RL,Pave,Reg,Lvl,Inside,Mod,Norm,Norm,1Fam,2Story,...,Typ,TA,Attchd,Fin,TA,TA,Y,WD,Normal,test

In [71]:
df['FireplaceQu'].fillna(df['FireplaceQu'].mode()[0],inplace=True)

In [76]:
for col in category_col:
    df[col].fillna(df[col].mode()[0],inplace=True)

In [78]:
df[category_col].isna().sum()

MSZoning         0
Street           0
LotShape         0
LandContour      0
LotConfig        0
LandSlope        0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
RoofStyle        0
RoofMatl         0
MasVnrType       0
ExterQual        0
ExterCond        0
Foundation       0
BsmtQual         0
BsmtCond         0
BsmtExposure     0
BsmtFinType1     0
BsmtFinType2     0
Heating          0
HeatingQC        0
CentralAir       0
Electrical       0
KitchenQual      0
Functional       0
FireplaceQu      0
GarageType       0
GarageFinish     0
GarageQual       0
GarageCond       0
PavedDrive       0
SaleType         0
SaleCondition    0
Source           0
dtype: int64

In [80]:
train = df.loc[df['Source']=='train']
test = df.loc[df['Source']=='test']

In [84]:
train.columns[train.isna().sum()>=1]

Index([], dtype='object')

In [83]:
test.columns[test.isna().sum()>=1]

Index(['SalePrice'], dtype='object')

In [92]:
train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,...,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Source
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,Inside,Gtl,...,TA,Y,0,61,2,2008,WD,Normal,208500.0,train
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,FR2,Gtl,...,TA,Y,298,0,5,2007,WD,Normal,181500.0,train
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,Inside,Gtl,...,TA,Y,0,42,9,2008,WD,Normal,223500.0,train
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,Corner,Gtl,...,TA,Y,0,35,2,2006,WD,Abnorml,140000.0,train
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,FR2,Gtl,...,TA,Y,192,84,12,2008,WD,Normal,250000.0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Reg,Lvl,Inside,Gtl,...,TA,Y,0,40,8,2007,WD,Normal,175000.0,train
1456,1457,20,RL,85.0,13175,Pave,Reg,Lvl,Inside,Gtl,...,TA,Y,349,0,2,2010,WD,Normal,210000.0,train
1457,1458,70,RL,66.0,9042,Pave,Reg,Lvl,Inside,Gtl,...,TA,Y,0,60,5,2010,WD,Normal,266500.0,train
1458,1459,20,RL,68.0,9717,Pave,Reg,Lvl,Inside,Gtl,...,TA,Y,366,0,4,2010,WD,Normal,142125.0,train
1459,1460,20,RL,75.0,9937,Pave,Reg,Lvl,Inside,Gtl,...,TA,Y,0,68,6,2008,WD,Normal,147500.0,train

In [95]:
X = train.select_dtypes(include=np.number).drop(columns =['SalePrice','Id'])
X.columns

Index(['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtUnfSF',
       'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'GrLivArea', 'BsmtFullBath',
       'FullBath', 'HalfBath', 'BedroomAbvGr', 'TotRmsAbvGrd', 'Fireplaces',
       'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'MoSold', 'YrSold'],
      dtype='object')

In [96]:
vif_data = pd.DataFrame()
vif_data['features']=X.columns
vif_data

        features
0     MSSubClass
1    LotFrontage
2        LotArea
3    OverallQual
4    OverallCond
5      YearBuilt
6   YearRemodAdd
7     MasVnrArea
8     BsmtFinSF1
9      BsmtUnfSF
10   TotalBsmtSF
11      1stFlrSF
12      2ndFlrSF
13     GrLivArea
14  BsmtFullBath
15      FullBath
16      HalfBath
17  BedroomAbvGr
18  TotRmsAbvGrd
19    Fireplaces
20   GarageYrBlt
21    GarageCars
22    GarageArea
23    WoodDeckSF
24   OpenPorchSF
25        MoSold
26        YrSold

In [99]:
vif_data['VIF'] = [variance_inflation_factor(X.values,i) for i in range(len(X.columns))]

In [100]:
vif_data

        features           VIF
0     MSSubClass      5.439775
1    LotFrontage     37.623731
2        LotArea     16.043968
3    OverallQual     57.052291
4    OverallCond     60.659613
5      YearBuilt  17826.392328
6   YearRemodAdd  19242.455559
7     MasVnrArea      1.602976
8     BsmtFinSF1      6.264996
9      BsmtUnfSF      6.765497
10   TotalBsmtSF     46.904399
11      1stFlrSF     61.238394
12      2ndFlrSF      8.314022
13     GrLivArea     60.576299
14  BsmtFullBath      3.163146
15      FullBath     23.473314
16      HalfBath      3.348254
17  BedroomAbvGr     34.333273
18  TotRmsAbvGrd     61.745423
19    Fireplaces      2.851215
20   GarageYrBlt  21633.284866
21    GarageCars     36.832882
22    GarageArea     31.808234
23    WoodDeckSF      1.847014
24   OpenPorchSF      2.068706
25        MoSold      6.588374
26        YrSold  21981.901291

In [126]:
vif_data

        features        VIF
0     MSSubClass   4.947191
1    LotFrontage  33.051793
2        LotArea  15.985162
3    OverallQual  46.228920
4    OverallCond  28.286012
5     MasVnrArea   1.560616
6     BsmtFinSF1   6.250111
7      BsmtUnfSF   6.742458
8    TotalBsmtSF  45.005144
9       1stFlrSF  58.265678
10      2ndFlrSF   7.496902
11     GrLivArea  60.491118
12  BsmtFullBath   3.115127
13      FullBath  19.709178
14      HalfBath   2.970073
15  BedroomAbvGr  32.472254
16  TotRmsAbvGrd  59.933453
17    Fireplaces   2.674272
18    GarageCars  35.720945
19    GarageArea  30.744462
20    WoodDeckSF   1.795441
21   OpenPorchSF   2.041611
22        MoSold   6.380094